import type { EventRecord } from "@/lib/types";

// Fictional event listings for product demonstration only. Photography is served by
// Unsplash and credited in the event detail view. No event implies a real affiliation.
export const events: EventRecord[] = [
  {
    id: "coffee-crawl-daan",
    title: "Slow Coffee Crawl: Da’an",
    description: "Spend a late morning walking between three independent coffee bars, comparing light-roast pour-overs and meeting the people behind each counter. Tastings are included and the pace is intentionally unhurried.",
    image: "https://images.unsplash.com/photo-1445116572660-236099ec97a0?auto=format&fit=crop&w=1600&q=85",
    imageAlt: "Warmly lit independent coffee shop interior",
    imageCredit: "Unsplash",
    imageCreditUrl: "https://unsplash.com/",
    startAt: "2026-10-10T10:00:00+08:00", endAt: "2026-10-10T13:00:00+08:00",
    venue: "Paper Street Coffee", address: "No. 28, Lane 113, Xinyi Rd., Da’an District", city: "Taipei",
    latitude: 25.0334, longitude: 121.5434, price: 650, currency: "TWD", category: "Coffee", vibes: ["Relaxed", "Social"], organizer: "Small Cup Society", registrationUrl: null,
  },
  {
    id: "night-sketch-songshan",
    title: "After-dark Urban Sketch Walk",
    description: "Bring any sketchbook and follow a local illustrator through Songshan’s glowing alleys. We’ll pause for quick perspective prompts, share pages, and end with a night-market snack.",
    image: "https://images.unsplash.com/photo-1549490349-8643362247b5?auto=format&fit=crop&w=1600&q=85",
    imageAlt: "Colorful paint and art materials",
    imageCredit: "Unsplash", imageCreditUrl: "https://unsplash.com/",
    startAt: "2026-10-11T18:30:00+08:00", endAt: "2026-10-11T21:00:00+08:00",
    venue: "Songshan Cultural Park", address: "No. 133, Guangfu S. Rd., Xinyi District", city: "Taipei",
    latitude: 25.0437, longitude: 121.5606, price: 300, currency: "TWD", category: "Arts & Culture", vibes: ["Relaxed", "Hands-on"], organizer: "Night Lines Taipei", registrationUrl: null,
  },
  {
    id: "founder-breakfast",
    title: "Founder Breakfast: First 100 Users",
    description: "A candid roundtable for early-stage builders. Four founders share the experiments that found their first customers, followed by small-group problem solving over breakfast.",
    image: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=1600&q=85",
    imageAlt: "People collaborating around a laptop at a bright table",
    imageCredit: "Unsplash", imageCreditUrl: "https://unsplash.com/",
    startAt: "2026-10-14T08:00:00+08:00", endAt: "2026-10-14T10:00:00+08:00",
    venue: "Futureward Central", address: "No. 1, Bade Rd. Sec. 1, Zhongzheng District", city: "Taipei",
    latitude: 25.0431, longitude: 121.5304, price: 450, currency: "TWD", category: "Entrepreneurship", vibes: ["Professional", "Social"], organizer: "First Mile Club", registrationUrl: null,
  },
  {
    id: "ceramics-studio",
    title: "Make a Wabi-sabi Coffee Cup",
    description: "Shape and texture your own stoneware cup in a beginner-friendly hand-building session. The studio will glaze and fire every piece for later collection.",
    image: "https://images.unsplash.com/photo-1610701596007-11502861dcfa?auto=format&fit=crop&w=1600&q=85",
    imageAlt: "Hands shaping clay in a ceramics studio",
    imageCredit: "Unsplash", imageCreditUrl: "https://unsplash.com/",
    startAt: "2026-10-17T14:00:00+08:00", endAt: "2026-10-17T16:30:00+08:00",
    venue: "Muddy Hands Studio", address: "No. 56, Chifeng St., Datong District", city: "Taipei",
    latitude: 25.0558, longitude: 121.5205, price: 1200, currency: "TWD", category: "Workshops", vibes: ["Hands-on", "Relaxed"], organizer: "Muddy Hands Studio", registrationUrl: null,
  },
  {
    id: "ai-prototyping-lab",
    title: "Practical AI Prototyping Lab",
    description: "Turn a service idea into a testable prototype in one evening. Facilitators cover prompt structures, simple evaluation, and honest ways to communicate where automation is used.",
    image: "https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&w=1600&q=85",
    imageAlt: "Workshop participants talking around a table",
    imageCredit: "Unsplash", imageCreditUrl: "https://unsplash.com/",
    startAt: "2026-10-20T19:00:00+08:00", endAt: "2026-10-20T21:30:00+08:00",
    venue: "Taipei Co-Space", address: "No. 12, Keelung Rd. Sec. 1, Xinyi District", city: "Taipei",
    latitude: 25.0481, longitude: 121.5654, price: 800, currency: "TWD", category: "Technology", vibes: ["Hands-on", "Professional"], organizer: "Prototype Tuesdays", registrationUrl: null,
  },
  {
    id: "riverside-jazz-picnic",
    title: "Riverside Jazz Picnic",
    description: "An easygoing sunset session with two Taipei jazz trios. Bring a blanket and your own snacks; a small community drinks stand supports the performers.",
    image: "https://images.unsplash.com/photo-1506157786151-b8491531f063?auto=format&fit=crop&w=1600&q=85",
    imageAlt: "Outdoor concert crowd at golden hour",
    imageCredit: "Unsplash", imageCreditUrl: "https://unsplash.com/",
    startAt: "2026-10-24T16:30:00+08:00", endAt: "2026-10-24T20:00:00+08:00",
    venue: "Dajia Riverside Park", address: "Binjiang St., Zhongshan District", city: "Taipei",
    latitude: 25.0755, longitude: 121.5416, price: 0, currency: "TWD", category: "Music", vibes: ["Relaxed", "Social"], organizer: "River Notes Collective", registrationUrl: null,
  },
  {
    id: "yangmingshan-photo-hike",
    title: "Misty Mountain Photo Hike",
    description: "A gentle trail session focused on framing, atmosphere, and phone photography. The route is beginner-friendly, with frequent stops and a shared bus from central Taipei.",
    image: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1600&q=85",
    imageAlt: "Hiker overlooking a misty green landscape",
    imageCredit: "Unsplash", imageCreditUrl: "https://unsplash.com/",
    startAt: "2026-10-25T07:30:00+08:00", endAt: "2026-10-25T13:00:00+08:00",
    venue: "Yangmingshan Trailhead", address: "Zhuzihu Rd., Beitou District", city: "Taipei",
    latitude: 25.1666, longitude: 121.5635, price: 500, currency: "TWD", category: "Outdoors", vibes: ["Relaxed", "Social"], organizer: "Outside Frame", registrationUrl: null,
  },
  {
    id: "type-design-clinic",
    title: "Type Design Critique Clinic",
    description: "Bring a work in progress—from a poster to a product screen—for a generous, structured critique. The session opens with a compact lesson on rhythm and hierarchy.",
    image: "https://images.unsplash.com/photo-1561070791-2526d30994b5?auto=format&fit=crop&w=1600&q=85",
    imageAlt: "Designer working with color swatches and typography",
    imageCredit: "Unsplash", imageCreditUrl: "https://unsplash.com/",
    startAt: "2026-10-28T19:00:00+08:00", endAt: "2026-10-28T21:00:00+08:00",
    venue: "Design Pin Lab", address: "No. 1, Yumen St., Zhongshan District", city: "Taipei",
    latitude: 25.0702, longitude: 121.5201, price: 350, currency: "TWD", category: "Design", vibes: ["Professional", "Hands-on"], organizer: "Type Friends Taipei", registrationUrl: null,
  },
  {
    id: "vinyl-listening-room",
    title: "Vinyl Listening Room: City Pop",
    description: "A seated, phone-away listening night tracing city pop from late-70s grooves to modern revivals. A record collector introduces each side before the needle drops.",
    image: "https://images.unsplash.com/photo-1461360228754-6e81c478b882?auto=format&fit=crop&w=1600&q=85",
    imageAlt: "Vinyl record playing on a turntable",
    imageCredit: "Unsplash", imageCreditUrl: "https://unsplash.com/",
    startAt: "2026-10-30T20:00:00+08:00", endAt: "2026-10-30T22:00:00+08:00",
    venue: "Needle & Room", address: "No. 87, Wenchang St., Da’an District", city: "Taipei",
    latitude: 25.0321, longitude: 121.5501, price: 400, currency: "TWD", category: "Music", vibes: ["Relaxed", "Social"], organizer: "Needle & Room", registrationUrl: null,
  },
  {
    id: "creative-coding-sunday",
    title: "Creative Coding Sunday",
    description: "Experiment with generative forms and sound in the browser. Short prompts replace long lectures, and beginners can pair with volunteer mentors throughout the afternoon.",
    image: "https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&w=1600&q=85",
    imageAlt: "Code on a laptop screen in a dark room",
    imageCredit: "Unsplash", imageCreditUrl: "https://unsplash.com/",
    startAt: "2026-11-01T13:00:00+08:00", endAt: "2026-11-01T17:00:00+08:00",
    venue: "Open Corner", address: "No. 92, Roosevelt Rd. Sec. 3, Zhongzheng District", city: "Taipei",
    latitude: 25.0195, longitude: 121.5292, price: 0, currency: "TWD", category: "Technology", vibes: ["Hands-on", "Social"], organizer: "Code Sketch Club", registrationUrl: null,
  },
  {
    id: "zine-making",
    title: "One-night Zine Making Club",
    description: "Cut, paste, photocopy, and leave with a tiny edition of your own eight-page zine. Materials, prompts, and a communal table are provided.",
    image: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?auto=format&fit=crop&w=1600&q=85",
    imageAlt: "Open art book on a creative worktable",
    imageCredit: "Unsplash", imageCreditUrl: "https://unsplash.com/",
    startAt: "2026-11-05T18:30:00+08:00", endAt: "2026-11-05T21:30:00+08:00",
    venue: "Corner Print Room", address: "No. 16, Dihua St. Sec. 1, Datong District", city: "Taipei",
    latitude: 25.0546, longitude: 121.5102, price: 550, currency: "TWD", category: "Workshops", vibes: ["Hands-on", "Social"], organizer: "Tiny Editions", registrationUrl: null,
  },
  {
    id: "indie-maker-demo-night",
    title: "Indie Maker Demo Night",
    description: "Five local makers show what they are building in fast, honest demos. No pitch decks: just products, lessons, and plenty of time to meet fellow builders.",
    image: "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?auto=format&fit=crop&w=1600&q=85",
    imageAlt: "Speaker presenting to an audience in a modern room",
    imageCredit: "Unsplash", imageCreditUrl: "https://unsplash.com/",
    startAt: "2026-11-07T18:00:00+08:00", endAt: "2026-11-07T21:00:00+08:00",
    venue: "North Gate Commons", address: "No. 8, Zhongxiao W. Rd., Zhongzheng District", city: "Taipei",
    latitude: 25.0473, longitude: 121.5152, price: 200, currency: "TWD", category: "Entrepreneurship", vibes: ["Professional", "Social"], organizer: "Build Small Taipei", registrationUrl: null,
  },
  {
    id: "museum-slow-looking",
    title: "Slow Looking at the Museum",
    description: "Spend an hour with only three artworks. A facilitator offers observation prompts, then opens an informal conversation over tea in the museum courtyard.",
    image: "https://images.unsplash.com/photo-1561214115-f2f134cc4912?auto=format&fit=crop&w=1600&q=85",
    imageAlt: "Visitors walking through a contemporary gallery",
    imageCredit: "Unsplash", imageCreditUrl: "https://unsplash.com/",
    startAt: "2026-11-08T14:00:00+08:00", endAt: "2026-11-08T16:00:00+08:00",
    venue: "Taipei Fine Arts Museum", address: "No. 181, Zhongshan N. Rd. Sec. 3, Zhongshan District", city: "Taipei",
    latitude: 25.0726, longitude: 121.5247, price: 30, currency: "TWD", category: "Arts & Culture", vibes: ["Relaxed"], organizer: "Take Your Time Club", registrationUrl: null,
  },
  {
    id: "product-storytelling",
    title: "Product Storytelling Workshop",
    description: "Practice turning features into clear, specific stories. You’ll rewrite one real product message, test it with a partner, and leave with a reusable narrative template.",
    image: "https://images.unsplash.com/photo-1456324504439-367cee3b3c32?auto=format&fit=crop&w=1600&q=85",
    imageAlt: "Notebook and pencil on a clean desk",
    imageCredit: "Unsplash", imageCreditUrl: "https://unsplash.com/",
    startAt: "2026-11-12T19:00:00+08:00", endAt: "2026-11-12T21:30:00+08:00",
    venue: "The Workshop Taipei", address: "No. 20, Ren’ai Rd. Sec. 3, Da’an District", city: "Taipei",
    latitude: 25.0385, longitude: 121.5379, price: 900, currency: "TWD", category: "Design", vibes: ["Hands-on", "Professional"], organizer: "Clear Words Studio", registrationUrl: null,
  },
  {
    id: "tea-trail-maokong",
    title: "Maokong Tea Trail & Tasting",
    description: "Follow a shaded hillside path to a family-run teahouse, then taste three local teas with a simple brewing lesson. Cable-car fare is not included.",
    image: "https://images.unsplash.com/photo-1545048702-79362596cdc9?auto=format&fit=crop&w=1600&q=85",
    imageAlt: "Green tea plantation across rolling hills",
    imageCredit: "Unsplash", imageCreditUrl: "https://unsplash.com/",
    startAt: "2026-11-15T09:00:00+08:00", endAt: "2026-11-15T13:00:00+08:00",
    venue: "Maokong Gondola Station", address: "Lane 38, Section 3, Zhinan Rd., Wenshan District", city: "Taipei",
    latitude: 24.9686, longitude: 121.5882, price: 700, currency: "TWD", category: "Outdoors", vibes: ["Relaxed", "Social"], organizer: "Taipei Trail Table", registrationUrl: null,
  },
  {
    id: "latte-art-basics",
    title: "Latte Art Without the Pressure",
    description: "Learn milk texture, pouring height, and the basic heart in a tiny evening class. Every guest gets multiple attempts and plenty of coffee to taste.",
    image: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=1600&q=85",
    imageAlt: "Latte art in a ceramic cup",
    imageCredit: "Unsplash", imageCreditUrl: "https://unsplash.com/",
    startAt: "2026-11-18T18:30:00+08:00", endAt: "2026-11-18T20:30:00+08:00",
    venue: "Good Day Coffee Lab", address: "No. 41, Jinzhou St., Zhongshan District", city: "Taipei",
    latitude: 25.0603, longitude: 121.5249, price: 950, currency: "TWD", category: "Coffee", vibes: ["Hands-on", "Relaxed"], organizer: "Good Day Coffee Lab", registrationUrl: null,
  },
];

export function getEvent(id: string) {
  return events.find((event) => event.id === id);
}
